server:
  port: 0

spring:
  application:
    name: serie-service
  mongodb:
    embedded:
      version: 4.0.2
  sleuth:
    enabled: true
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  data:
    mongodb:
      database: test
      port: 27017


